### ISSUE TITLE
Add YOLO model

### ISSUE THREAD

**Issue by samminhch** [MHSeals/ROS2-Docker-Development#7]
branch #2 
---

In `buoy_detection/buoy_detection/processed.py`, the buoy detection model was declared, but `best.pt ` is missing from the package. It needs to be in that package in order for that node to run correctly. I'm not sure who has that file, but if you guys could commit that file to the branch that would be great!

```python
class BuoyDetectionPublisher(Node):
    def __init__(self):
        self._model = YOLO('best.pt')   # <-- this line right here!
        super().__init__('ai')
        
        # subscribe to image processing node
        self.subscription = self.create_subscription(
            msg_type=Image,
            topic='/camera/color/image_raw',
            callback=self.image_callback,
            qos_profile=10
        )
        
        # publish to processed node
        self.publisher = self.create_publisher(
            msg_type=Image, 
            topic='processed', 
            qos_profile=10
        )
```

**Comment by alec-jensen** [comment]
`best.pt` is the model weights. Can be found [here](https://github.com/MHSeals/buoy-model/releases)
